import { Instrument } from './types';

export const ASSETS: Instrument[] = [
  // FOREX - MAJOR PAIRS
  {
    id: 'eurusd',
    symbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    assetClass: 'forex',
    quoteCurrency: 'USD',
    baseCurrency: 'EUR',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.0001,
    tickSize: 0.00001,
    decimalPrecision: 5,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'gbpusd',
    symbol: 'GBP/USD',
    name: 'British Pound / US Dollar',
    assetClass: 'forex',
    quoteCurrency: 'USD',
    baseCurrency: 'GBP',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.0001,
    tickSize: 0.00001,
    decimalPrecision: 5,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'usdjpy',
    symbol: 'USD/JPY',
    name: 'US Dollar / Japanese Yen',
    assetClass: 'forex',
    quoteCurrency: 'JPY',
    baseCurrency: 'USD',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.01,
    tickSize: 0.001,
    decimalPrecision: 3,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'usdchf',
    symbol: 'USD/CHF',
    name: 'US Dollar / Swiss Franc',
    assetClass: 'forex',
    quoteCurrency: 'CHF',
    baseCurrency: 'USD',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.0001,
    tickSize: 0.00001,
    decimalPrecision: 5,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'audusd',
    symbol: 'AUD/USD',
    name: 'Australian Dollar / US Dollar',
    assetClass: 'forex',
    quoteCurrency: 'USD',
    baseCurrency: 'AUD',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.0001,
    tickSize: 0.00001,
    decimalPrecision: 5,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'usdcad',
    symbol: 'USD/CAD',
    name: 'US Dollar / Canadian Dollar',
    assetClass: 'forex',
    quoteCurrency: 'CAD',
    baseCurrency: 'USD',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.0001,
    tickSize: 0.00001,
    decimalPrecision: 5,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'nzdusd',
    symbol: 'NZD/USD',
    name: 'New Zealand Dollar / US Dollar',
    assetClass: 'forex',
    quoteCurrency: 'USD',
    baseCurrency: 'NZD',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.0001,
    tickSize: 0.00001,
    decimalPrecision: 5,
    minQuantity: 1000,
    quantityStep: 1000,
  },

  // FOREX - MAJOR CROSSES
  {
    id: 'eurgbp',
    symbol: 'EUR/GBP',
    name: 'Euro / British Pound',
    assetClass: 'forex',
    quoteCurrency: 'GBP',
    baseCurrency: 'EUR',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.0001,
    tickSize: 0.00001,
    decimalPrecision: 5,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'eurjpy',
    symbol: 'EUR/JPY',
    name: 'Euro / Japanese Yen',
    assetClass: 'forex',
    quoteCurrency: 'JPY',
    baseCurrency: 'EUR',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.01,
    tickSize: 0.001,
    decimalPrecision: 3,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'gbpjpy',
    symbol: 'GBP/JPY',
    name: 'British Pound / Japanese Yen',
    assetClass: 'forex',
    quoteCurrency: 'JPY',
    baseCurrency: 'GBP',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.01,
    tickSize: 0.001,
    decimalPrecision: 3,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'euraud',
    symbol: 'EUR/AUD',
    name: 'Euro / Australian Dollar',
    assetClass: 'forex',
    quoteCurrency: 'AUD',
    baseCurrency: 'EUR',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.0001,
    tickSize: 0.00001,
    decimalPrecision: 5,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'gbpaud',
    symbol: 'GBP/AUD',
    name: 'British Pound / Australian Dollar',
    assetClass: 'forex',
    quoteCurrency: 'AUD',
    baseCurrency: 'GBP',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.0001,
    tickSize: 0.00001,
    decimalPrecision: 5,
    minQuantity: 1000,
    quantityStep: 1000,
  },
  {
    id: 'audjpy',
    symbol: 'AUD/JPY',
    name: 'Australian Dollar / Japanese Yen',
    assetClass: 'forex',
    quoteCurrency: 'JPY',
    baseCurrency: 'AUD',
    contractSize: 100000,
    lotSize: 100000,
    pipSize: 0.01,
    tickSize: 0.001,
    decimalPrecision: 3,
    minQuantity: 1000,
    quantityStep: 1000,
  },

  // COMMODITIES
  {
    id: 'xauusd',
    symbol: 'XAU/USD',
    name: 'Gold',
    assetClass: 'commodity',
    quoteCurrency: 'USD',
    contractSize: 100, // 100 oz per lot usually
    lotSize: 100,
    pipSize: 0.01,
    tickSize: 0.01,
    decimalPrecision: 2,
    minQuantity: 1, // 0.01 lots = 1 oz
    quantityStep: 1,
  },
  {
    id: 'xagusd',
    symbol: 'XAG/USD',
    name: 'Silver',
    assetClass: 'commodity',
    quoteCurrency: 'USD',
    contractSize: 5000, // 5000 oz per lot usually
    lotSize: 5000,
    pipSize: 0.01,
    tickSize: 0.001,
    decimalPrecision: 3,
    minQuantity: 50, // 0.01 lots = 50 oz
    quantityStep: 50,
  },
  {
    id: 'wtiusd',
    symbol: 'WTI / USOIL',
    name: 'Crude Oil',
    assetClass: 'commodity',
    quoteCurrency: 'USD',
    contractSize: 1000, // 1000 barrels
    lotSize: 1000,
    pipSize: 0.01,
    tickSize: 0.01,
    decimalPrecision: 2,
    minQuantity: 10, // 0.01 lots
    quantityStep: 10,
  },
  {
    id: 'brentusd',
    symbol: 'Brent / UKOIL',
    name: 'Brent Crude',
    assetClass: 'commodity',
    quoteCurrency: 'USD',
    contractSize: 1000,
    lotSize: 1000,
    pipSize: 0.01,
    tickSize: 0.01,
    decimalPrecision: 2,
    minQuantity: 10,
    quantityStep: 10,
  },
  {
    id: 'natgas',
    symbol: 'Natural Gas',
    name: 'Natural Gas',
    assetClass: 'commodity',
    quoteCurrency: 'USD',
    contractSize: 10000, // 10,000 MMBtu
    lotSize: 10000,
    pipSize: 0.001,
    tickSize: 0.001,
    decimalPrecision: 3,
    minQuantity: 100, // 0.01 lots
    quantityStep: 100,
  },

  // CRYPTO
  {
    id: 'btcusd',
    symbol: 'BTC/USD',
    name: 'Bitcoin / US Dollar',
    assetClass: 'crypto',
    quoteCurrency: 'USD',
    contractSize: 1,
    lotSize: 1, // Lots don't really matter as much here, we use quantity
    pipSize: 1,
    tickSize: 0.01,
    decimalPrecision: 2,
    minQuantity: 0.001,
    quantityStep: 0.001,
  },
  {
    id: 'ethusd',
    symbol: 'ETH/USD',
    name: 'Ethereum / US Dollar',
    assetClass: 'crypto',
    quoteCurrency: 'USD',
    contractSize: 1,
    lotSize: 1,
    pipSize: 0.1,
    tickSize: 0.01,
    decimalPrecision: 2,
    minQuantity: 0.01,
    quantityStep: 0.01,
  },
  {
    id: 'btcusdt',
    symbol: 'BTC/USDT',
    name: 'Bitcoin / Tether',
    assetClass: 'crypto',
    quoteCurrency: 'USDT',
    contractSize: 1,
    lotSize: 1,
    pipSize: 1,
    tickSize: 0.01,
    decimalPrecision: 2,
    minQuantity: 0.001,
    quantityStep: 0.001,
  },
  {
    id: 'ethusdt',
    symbol: 'ETH/USDT',
    name: 'Ethereum / Tether',
    assetClass: 'crypto',
    quoteCurrency: 'USDT',
    contractSize: 1,
    lotSize: 1,
    pipSize: 0.1,
    tickSize: 0.01,
    decimalPrecision: 2,
    minQuantity: 0.01,
    quantityStep: 0.01,
  },
  {
    id: 'solusd',
    symbol: 'SOL/USD',
    name: 'Solana / US Dollar',
    assetClass: 'crypto',
    quoteCurrency: 'USD',
    contractSize: 1,
    lotSize: 1,
    pipSize: 0.01,
    tickSize: 0.01,
    decimalPrecision: 2,
    minQuantity: 0.1,
    quantityStep: 0.1,
  },
  {
    id: 'xrpusd',
    symbol: 'XRP/USD',
    name: 'Ripple / US Dollar',
    assetClass: 'crypto',
    quoteCurrency: 'USD',
    contractSize: 1,
    lotSize: 1,
    pipSize: 0.0001,
    tickSize: 0.0001,
    decimalPrecision: 4,
    minQuantity: 1,
    quantityStep: 1,
  },
];

export const getAssetById = (id: string): Instrument | undefined => {
  return ASSETS.find(a => a.id === id);
};
